[general]
working_directory = "c:/users/herma"
import = [
"~/.config/alacritty/themes/rose-pine.toml",
]

[terminal]
shell = "nu"

[font]
size = 13.0

[font.normal]
family = "Cascadia Code"
style = "Regular"

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.bold_italic]
family = "Cascadia Code"
style = "Bold Italic"

[window]
opacity = 0.97
padding = { x = 5, y = 5 }

[cursor]
style = "Block"

